# Generated by Django 4.2.7 on 2024-02-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Hey there, Nice to meet you', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='John Doe (Default)', max_length=200, null=True),
        ),
    ]
