# Generated by Django 4.2.7 on 2024-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_desc_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Hey there, nice to meet you', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User (Default)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default="Please change your username and other info from the below 'Edit' option.", max_length=200, null=True),
        ),
    ]
