# Generated by Django 4.2.7 on 2024-02-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_desc_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Hey there, nice to meet you.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default="Please give your name and other info from the below 'Edit' option.", max_length=200, null=True),
        ),
    ]
