# Generated by Django 4.2.7 on 2024-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_desc_alter_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='Please enter your date of birth', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(default='Please enter your NID number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(default='Please enter your number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Enter your address', max_length=200, null=True),
        ),
    ]
