# Generated by Django 4.2.7 on 2024-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_alter_profile_desc_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='dd-mm-yy', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.IntegerField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default='', max_length=11, null=True),
        ),
    ]
