# Generated by Django 4.2.7 on 2024-03-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_dob_alter_profile_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default='', null=True),
        ),
    ]
