# Generated by Django 4.2.7 on 2024-03-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_alter_profile_dob_alter_profile_nid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('complaint_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
